name: tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_call: { }

jobs:
  pest:
    runs-on: ubuntu-latest
    env:
      APP_ENV: testing
      APP_KEY: base64:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=
      DB_CONNECTION: testing

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, bcmath, pdo, pdo_sqlite, sqlite3
          coverage: none
          ini-values: error_reporting=E_ALL, display_errors=On

      - name: Quick check extensions
        run: |
          php -r 'foreach(["pdo","pdo_sqlite","sqlite3"] as $e){echo $e.": ".(extension_loaded($e)?"yes":"no").PHP_EOL;};'

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --no-progress

      - name: Dump autoload
        run: composer dump-autoload -o

      - name: Run tests (verbose)
        run: php vendor/bin/pest -vvv