name: tests

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  pest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, bcmath, pdo, sqlite
          coverage: none
          ini-values: error_reporting=E_ALL, display_errors=On

      - name: Validate composer.json
        run: composer validate --no-check-publish

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --no-progress

      # Zet basis env zodat Testbench nooit klaagt
      - name: Prepare env
        run: |
          echo "APP_ENV=testing" >> $GITHUB_ENV
          echo "APP_KEY=base64:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=" >> $GITHUB_ENV
          echo "DB_CONNECTION=testing" >> $GITHUB_ENV

      - name: Run tests
        run: vendor/bin/pest -v